"""add vip_expires_at to user

Revision ID: 2bc205f20d7e
Revises: cf39ce5c17f5
Create Date: 2025-06-27 16:39:48.147496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc205f20d7e'
down_revision = 'cf39ce5c17f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vip_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('vip_expires_at')

    # ### end Alembic commands ###
