"""add last_free_credits_refresh to user

Revision ID: 7688d262bbc4
Revises: 2bc205f20d7e
Create Date: 2025-06-27 16:55:10.931469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7688d262bbc4'
down_revision = '2bc205f20d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_free_credits_refresh', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_free_credits_refresh')

    # ### end Alembic commands ###
